export enum FooterSection { 
    CONTENT_RESPONSIBLE = 'Nguyễn Thị Mai Phương',
    ORDER_INSTRUCTIONS = 'ORDER_INSTRUCTIONS',
    PAYMENT_INSTRUCTIONS = 'PAYMENT_INSTRUCTIONS',
    CONTACT = 'CONTACT',
}