export const QUERYKEY = {
  profile: ['profile'],
  branches: ['branches'],
  catalog: ['catalog'],
  chefAreaPrinters: ['chefAreaPrinters'],
  productVariants: ['productVariants'],
  products: ['products'],
  giftCards: ['giftCards'],
  cardOrder: ['cardOrder'],
  vouchers: ['vouchers'],
  specificVoucher: ['specificVoucher'],
  voucherGroups: ['voucherGroups'],
  vouchersForOrder: ['vouchersForOrder'],
  promotions: ['promotions'],
  banners: ['banners'],
  tables: ['tables'],
  roles: ['roles'],
  chefAreas: ['chefAreas'],
  chefOrders: ['chefOrders'],
  chefAreaProducts: ['chefAreaProducts'],
  notifications: ['notifications'],
  revenue: ['revenue'],
  userGiftCards: ['userGiftCards'],
  giftCardDetail: ['giftCardDetail'],
}
