name: deploy-cloud

on:
  push:
    branches:
      - cloud

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Environment Configuration
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
          echo "$ENV_PROD" > .deploy/cloud/.env

      - name: Deploy with Docker Compose
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_CLOUD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_CLOUD }}
          SSH_PORT: ${{ secrets.SSH_PORT_CLOUD }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_CLOUD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SSH_PORT $REMOTE_HOST >> ~/.ssh/known_hosts
          export DOCKER_HOST="ssh://$REMOTE_USER@$REMOTE_HOST:$SSH_PORT"

          # Export env. Docker swarm is not able to read .env file
          export $(grep -v '^#' .deploy/cloud/.env | xargs)

          docker compose -f .deploy/cloud/docker-compose.yml pull
          docker stack deploy -c .deploy/cloud/docker-compose.yml order_stack --detach=true

          # Remove exited containers
          docker rm $(docker ps -aq -f status=exited)

          # clean up none image after built
          docker image prune -f
