name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual trigger of the workflow

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: ${{ github.repository_owner }}

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional for multi-arch support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/dev-order-api
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/dev-order-ui
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/dev-postgres
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/dev-mysql

      - name: Build and push order-api image
        uses: docker/build-push-action@v4
        with:
          context: ./app/order-api
          file: ./.build/order-api/Dockerfile
          tags: ${{ steps.meta.outputs.tags['${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/dev-order-api'] }}
          labels: ${{ steps.meta.outputs.labels['${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/dev-order-api'] }}
          push: true
