name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual trigger of the workflow

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: ${{ github.repository_owner }}

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional for multi-arch support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push order-api image
        uses: docker/build-push-action@v4
        with:
          context: ./app/order-api
          file: ./.build/order-api/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-api:dev
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-api
          push: true

      - name: Build and push order-ui image
        uses: docker/build-push-action@v4
        with:
          context: ./app/order-ui
          file: ./.build/order-ui/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-ui:dev
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-ui
          push: true

      - name: Build and push postgres image
        uses: docker/build-push-action@v4
        with:
          context: ./.build/order-postgres
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/robot-db:dev
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/robot-db
          push: true

      - name: Build and push mysql image
        uses: docker/build-push-action@v4
        with:
          context: ./.build/order-db
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-db:dev
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-db
          push: true
