name: publish-prod

on:
  push:
    tags:
      - "v*" # This triggers the workflow on any tag

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: homeslands

jobs:
  publish-prod:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    environment: production

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional for multi-arch support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Environment Configuration
        env:
          GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS }}
          FE_ENV_PROD: ${{ secrets.FE_ENV_PROD }}
        run: |
          mkdir -p app/order-api/public/json
          echo "$GOOGLE_API_CREDENTIALS" > app/order-api/public/json/credentials.json
          echo "$FE_ENV_PROD" > app/order-ui/.env

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push order-api image
        uses: docker/build-push-action@v4
        with:
          context: ./app/order-api
          file: ./.build/order-api/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-api:latest
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-api
          push: true

      - name: Build and push order-ui image
        uses: docker/build-push-action@v4
        with:
          context: ./app/order-ui
          file: ./.build/order-ui/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-ui:latest
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-ui
          push: true
