name: publish-staging

on:
  push:
    branches:
      - staging

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: homeslands

jobs:
  publish-cloud:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    environment: staging

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This ensures all tags are fetched

      # Step 2: Set up Docker Buildx (optional for multi-arch support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Environment Configuration
        env:
          GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS }}
          FE_ENV: ${{ secrets.FE_ENV_STAGING }}
          AUTHORITIES: ${{ secrets.AUTHORITIES }}
        run: |
          mkdir -p app/order-api/public/json
          echo "$GOOGLE_API_CREDENTIALS" > app/order-api/public/json/credentials.json
          echo "$AUTHORITIES" > app/order-api/public/json/authorities.json
          echo "$FE_ENV" > app/order-ui/.env

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push order-api image
        uses: docker/build-push-action@v4
        with:
          context: ./app/order-api
          file: ./.build/order-api/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-api:staging
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-api
          push: true

      - name: Build and push order-ui image
        uses: docker/build-push-action@v4
        with:
          context: ./app/order-ui
          file: ./.build/order-ui/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-ui:staging
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/order-ui
          push: true
